galaxy_info:
  author: John Dreyer
  description: your role description
  license: MIT
  min_ansible_version: '2.1'

  platforms:
    - name: Ubuntu
      versions:
        - all

  galaxy_tags: []

dependencies: []
