---
- name: Set rust compiler to stable
  ansible.builtin.command: ~/.cargo/bin/rustup override set stable
  changed_when: true

- name: Update the stable rust compiler
  ansible.builtin.command: ~/.cargo/bin/rustup update stable
  changed_when: true

- name: Ensure alacritty build dependencies are installed
  become: true
  ansible.builtin.apt:
    name:
      - cmake
      - pkg-config
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
      - python3
    state: present

- name: Create open source directory
  ansible.builtin.file:
    path: ~/open-source/
    state: directory
    mode: "740"

- name: Clone alacritty repository
  ansible.builtin.git:
    repo: https://github.com/alacritty/alacritty.git
    dest: ~/open-source/alacritty
    version: master

- name: Build alacritty release binary
  ansible.builtin.command:
    chdir: ~/open-source/alacritty
    argv:
      - ~/.cargo/bin/cargo
      - build
      - --release
  changed_when: true

- name: Ensure alacritty release binary exists
  ansible.builtin.stat:
    path: ~/open-source/alacritty/target/release/alacritty
  register: alacritty
  failed_when: not alacritty.stat.exists

- name: Check if terminfo exists
  ansible.builtin.command: infocmp alacritty
  register: terminfo
  failed_when: false
  changed_when: true

- name: Add terminfo if needed
  ansible.builtin.command:
    chdir: ~/open-source/alacritty/
    argv:
      - tic
      - -xe
      - alacritty,alacritty-direct
      - extra/alacritty.info
  when: terminfo.rc != 0
  changed_when: true

- name: Copy build binary
  become: true
  ansible.builtin.command:
    argv:
      - cp 
      - ~/open-source/alacritty/target/release/alacritty
      - /usr/local/bin
  changed_when: true

- name: Copy alacritty icon
  become: true
  ansible.builtin.command:
    argv:
    - cp
    - ~/open-source/alacritty/extra/logo/alacritty-term.svg
    - /usr/share/pixmaps/Alacritty.svg
  changed_when: true

- name: Install alacritty desktop file
  become: true
  ansible.builtin.command:
    argv:
    - desktop-file-install
    - ~/open-source/alacritty/extra/linux/Alacritty.desktop
  changed_when: true

- name: Update desktop database
  become: true
  ansible.builtin.command:
    argv:
    - update-desktop-database
  changed_when: true
