---
- name: Download discord deb file
  ansible.builtin.get_url:
    url: https://discord.com/api/download?platform=linux&format=deb
    dest: /tmp/discord.deb
    mode: "0550"

- name: Install discord .deb package
  become: true
  ansible.builtin.apt:
    deb: /tmp/discord.deb

- name: Remove old deb file
  ansible.builtin.file:
    path: /tmp/discord.deb
    state: absent
