---
- name: Add Docker GPG key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
    force: true

# TODO: test {{ ansible_distribution_release }} here
- name: Add Docker repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Install Docker
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Add user to group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
      
- name: Enable docker service
  ansible.builtin.systemd:
    name: docker
    enabled: true

- name: Enable containerd service
  ansible.builtin.systemd:
    name: containerd
    enabled: true
