---
- name: Download NVM installation script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh
    dest: /tmp/install_nvm.sh
    mode: '0755'

- name: Run NVM installation script
  ansible.builtin.command: /tmp/install_nvm.sh creates=/home/{{ ansible_user }}/.nvm

- name: Load NVM environment
  ansible.builtin.shell: |
    export NVM_DIR="/home/{{ ansible_user }}/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
  args:
    executable: /bin/bash