---
- name: Download rust install script
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup.sh
    mode: "0550"

# TODO: Check if rust is present first
- name: Install rust
  ansible.builtin.command:
    argv:
      - /tmp/rustup.sh
      - -y
  changed_when: true
