---
- name: Packages | Sublime merge | Add Sublimes GPG key
  become: true
  ansible.builtin.get_url:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    dest: /etc/apt/trusted.gpg.d/sublimehq-pub.asc
    mode: "0644"
    force: true

- name: Packages | Sublime merge | Add Sublimes apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://download.sublimetext.com/ apt/stable/"
    state: present
    update_cache: true

- name: Packages | Sublime merge | Install Sublime merge
  become: true
  ansible.builtin.apt:
    name: sublime-merge
    state: present
