---
- name: Packages | VS Code | Add Microsoft GPG key
  become: true
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/trusted.gpg.d/microsoft.asc
    mode: "0644"
    force: true

- name: Packages | VS Code | Add Visual Studio Code repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
    state: present
    update_cache: true

- name: Packages | VS Code | Install Visual Studio Code
  become: true
  ansible.builtin.apt:
    name: code
    state: present
