#!/usr/bin/env ansible-playbook
---
- name: Setup development environment
  hosts: all
  become: true
  gather_facts: false

  roles:
    - packages
    - dotfiles
# not sure how best to split the roles...
